language: android
jdk: oraclejdk7
android:
    components:
        - build-tools-21.1.1
        - android-21
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
before_script:
    - chmod +x ./gradlew
script:
    - ./gradlew build
after_success:
    - echo "${TRAVIS_TAG}"
    - echo "${TRAVIS_BRANCH}"
    
