language: android
jdk: oraclejdk7
android:
    components:
        - build-tools-21.1.1
        - android-21
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
before_script:
    - chmod +x ./gradlew
    - chomd +x ./test.sh
script:
    - ./gradlew build
after_success:
    - ./test.sh
